# Site
title:              Казыят
bio:                Духовно-просветительский портал местной религиозной организации мусульман города Москвы «Казыят»
description:        "Moon is a minimal, one column jekyll theme for your blog."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'https://images.unsplash.com/photo-1415381266596-3975189f3277?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4b0a050066d523b4a6ea2371629a1ac2&auto=format&fit=crop&w=1955&q=80'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ru_RU
url:                http://kaziyat.ru

# Jekyll
permalink:          /post/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
#facebook:           username
#github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          noghay_world
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
vk:                 noghayhalk

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
